### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ozencb** [kgolid/topographic#1]
Hello, Kjetil

I have been checking your work recently and I really admire what you have done with P5.

I want to use some of your work on my personal website. Your p5yco repo has an MIT license, so I reckon I am free to use and modify those artworks but some of your repos (esp. topographic and tilework) are not licensed. Can you add licenses to those repos, if that's fine with you?

**Comment by kgolid** [comment]
Thank you for the kind words and the heads up! I have added an MIT license now; have fun!

Would love some credit if you decide to use any of it, though 😄
